### ISSUE TITLE
Add ability to reference existing sm instance in DA

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-secrets-manager#107]
### Description

As the SM DA is evolving to allow configuring the SM instance (adding engines), the SM DA should evolve to allow passing an existing sm instance (in other words optionally skip creating sm instance).

Similar pattern as for the key protect DA - so one aspect is to ensure there is consistency in variable names to skip creation / reusing existing instance. https://github.com/terraform-ibm-modules/terraform-ibm-kms-all-inclusive/blob/7c53a2d02ba92fbe7c4cd9215bd75d165db4516d/solutions/standard/variables.tf#L70

**Comment by vburckhardt** [comment]
Project is currently very limited in term of computing the value of Stacks. If existing_secrets_manager_crn is set, then any resource that would be created as part of the sm instance creation (key protect key) should be skipped.

 2024/04/29 11:31:02 [34mStarting command: terraform1.5 plan -input=false -refresh=true -state=terraform.tfstate -var-file=schematics.tfvars -no-color -out=tfplan.binary[39m[0m
 2024/04/29 11:31:02 Starting command: terraform1.5 plan -input=false -refresh=true -state=terraform.tfstate -var-file=schematics.tfvars -no-color -out=tfplan.binary
 2024/04/29 11:31:15 Terraform plan | 
 2024/04/29 11:31:15 Terraform plan | Terraform used the selected providers to generate the following execution
 2024/04/29 11:31:15 Terraform plan | plan. Resource actions are indicated with the following symbols:
 2024/04/29 11:31:15 Terraform plan |   + create
 2024/04/29 11:31:15 Terraform plan | 
 2024/04/29 11:31:15 Terraform plan | Terraform planned the following actions, but then encountered a problem:
 2024/04/29 11:31:15 Terraform plan | 
 2024/04/29 11:31:15 Terraform plan |   # module.resource_group.ibm_resource_group.resource_group[0] will be created
 2024/04/29 11:31:15 Terraform plan |   + resource "ibm_resource_group" "resource_group" {
 2024/04/29 11:31:15 Terraform plan |       + created_at          = (known after apply)
 2024/04/29 11:31:15 Terraform plan |       + crn                 = (known after apply)
 2024/04/29 11:31:15 Terraform plan |       + default             = (known after apply)
 2024/04/29 11:31:15 Terraform plan |       + id                  = (known after apply)
 2024/04/29 11:31:15 Terraform plan |       + name                = "0429-0429-stack-service-rg"
 2024/04/29 11:31:15 Terraform plan |       + payment_methods_url = (known after apply)
 2024/04/29 11:31:15 Terraform plan |       + quota_id            = (known after apply)
 2024/04/29 11:31:15 Terraform plan |       + quota_url           = (known after apply)
 2024/04/29 11:31:15 Terraform plan |       + resource_linkages   = (known after apply)
 2024/04/29 11:31:15 Terraform plan |       + state               = (known after apply)
 2024/04/29 11:31:15 Terraform plan |       + teams_url           = (known after apply)
 2024/04/29 11:31:15 Terraform plan |       + updated_at          = (known after apply)
 2024/04/29 11:31:15 Terraform plan |     }
 2024/04/29 11:31:15 Terraform plan | 
 2024/04/29 11:31:15 Terraform plan | Plan: 1 to add, 0 to change, 0 to destroy.
 2024/04/29 11:31:15 Terraform plan | 
 2024/04/29 11:31:15 Terraform plan | Changes to Outputs:
 2024/04/29 11:31:15 Terraform plan |   + resource_group_id      = (known after apply)
 2024/04/29 11:31:15 Terraform plan |   + resource_group_name    = "0429-0429-stack-service-rg"
 2024/04/29 11:31:15 Terraform plan |   + secrets_manager_region = "eu-de"
 2024/04/29 11:31:15 Terraform plan | 
 2024/04/29 11:31:15 Terraform plan | Error: Missing required argument
 2024/04/29 11:31:15 Terraform plan | 
 2024/04/29 11:31:15 Terraform plan |   with module.kms[0].module.kms_key_rings["0429-sm-cos-key-ring"].ibm_kms_key_rings.key_ring,
 2024/04/29 11:31:15 Terraform plan |   on .terraform/modules/kms.kms_key_rings/main.tf line 7, in resource "ibm_kms_key_rings" "key_ring":
 2024/04/29 11:31:15 Terraform plan |    7:   instance_id   = var.instance_id
 2024/04/29 11:31:15 Terraform plan | 
 2024/04/29 11:31:15 Terraform plan | The argument "instance_id" is required, but no definition was found.
 2024/04/29 11:31:15 Terraform plan | 
 2024/04/29 11:31:15 Terraform plan | Error: Error in function call
 2024/04/29 11:31:15 Terraform plan | 
 2024/04/29 11:31:15 Terraform plan |   on .terraform/modules/kms/main.tf line 22, in locals:
 2024/04/29 11:31:15 Terraform plan |   22:   existing_instance_validate_check = regex("^${local.existing_instance_validate_msg}$", (!local.existing_instance_validate_condition ? local.existing_instance_validate_msg : ""))
 2024/04/29 11:31:15 Terraform plan |     ├────────────────
 2024/04/29 11:31:15 Terraform plan |     │ while calling regex(pattern, string)
 2024/04/29 11:31:15 Terraform plan |     │ local.existing_instance_validate_condition is true
 2024/04/29 11:31:15 Terraform plan |     │ local.existing_instance_validate_msg is "A value must be provided for 'existing_key_protect_instance_guid' when 'create_key_protect_instance' is false"
 2024/04/29 11:31:15 Terraform plan | 
 2024/04/29 11:31:15 Terraform plan | Call to function "regex" failed: pattern did not match any part of the given
 2024/04/29 11:31:15 Terraform plan | string.
 2024/04/29 11:31:15 [1m[31mTerraform PLAN error: Terraform PLAN errorexit status 1[39m[0m

**Comment by ocofaigh** [comment]
Ah good catch @vburckhardt - the count needs to now be more advanced around the KMS key creation:
`count = var.existing_secrets_manager_kms_key_crn != null || var.existing_secrets_manager_crn != null`

**Comment by akocbek** [comment]
https://github.com/terraform-ibm-modules/terraform-ibm-secrets-manager/pull/110

**Comment by vburckhardt** [comment]
@akocbek 
Couple of more issues:
- resource group is created when passing sm crn - this should not be the case
- if existing_secrets_manager_kms_key_crn is null - then```
 │   on main.tf line 16, in locals:
│   16:   kms_key_crn       = var.existing_secrets_manager_kms_key_crn != null ? var.existing_secrets_manager_kms_key_crn : module.kms[0].keys[format("%s.%s", local.kms_key_ring_name, local.kms_key_name)].crn
│     ├────────────────
│     │ module.kms is empty tuple
```

**Comment by vburckhardt** [comment]
changing line 16 to   kms_key_crn       = var.existing_secrets_manager_crn == null ? (var.existing_secrets_manager_kms_key_crn != null ? var.existing_secrets_manager_kms_key_crn : module.kms[0].keys[format("%s.%s", local.kms_key_ring_name, local.kms_key_name)].crn) : null fixes the 2 issues

**Comment by vburckhardt** [comment]
One thing we'll need update on is adding an extra check to ensure resource_group is passed when sm crn is not set, now that this is optional in the inputs. I won't cover it in my PR (just covering minimum to get unblocked on a new version of the stack)

**Comment by akocbek** [comment]
resource group validation in https://github.com/terraform-ibm-modules/terraform-ibm-secrets-manager/pull/113

**Comment by ocofaigh** [comment]
Left a comment https://github.com/terraform-ibm-modules/terraform-ibm-secrets-manager/pull/113#pullrequestreview-2032348953
