### ISSUE TITLE
Adding EN to an already existing SM Instance

### ISSUE THREAD

**Issue by NinadKanchan** [terraform-ibm-modules/terraform-ibm-secrets-manager#132]
### Description
The current module does not handle registration of SM to EN instance if the SM already exists. A feature for the registration of the EN instance to existing SM would be helpful.

### New or affected modules

---

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by Khuzaima05** [comment]
PR merged closing this issue
