### ISSUE TITLE
`service_endpoints` should not allow `public`

### ISSUE THREAD

**Issue by ocofaigh** [terraform-ibm-modules/terraform-ibm-secrets-manager#49]
![image](https://github.com/terraform-ibm-modules/terraform-ibm-secrets-manager/assets/29608224/68c99e1a-a0cc-4635-9194-f1870f648a22)

Looks like there is no public option in the UI. If its not supported, it should be removed from the variable validation as an allowed value

**Comment by shemau** [comment]
PR created: https://github.com/terraform-ibm-modules/terraform-ibm-secrets-manager/pull/69
