### ISSUE TITLE
papercut: rich input definition missing

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-secrets-manager#76]
### Description

- kms_region 
- service_plan (use options in ibm_catalog.json for a drop down)
- region
- kms_endpoint_type (use options in ibm_catalog.json for a drop down)
- service_endpoints
- ...

### New or affected modules

---

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by akocbek** [comment]
has been addressed in https://github.com/terraform-ibm-modules/terraform-ibm-secrets-manager/pull/101
