### ISSUE TITLE
Expose ability to configure IAM engine in SM instance in DA

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-secrets-manager#77]
### Description

Using https://github.com/terraform-ibm-modules/terraform-ibm-secrets-manager-iam-engine

### New or affected modules

---

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by ocofaigh** [comment]
Included in https://github.com/terraform-ibm-modules/terraform-ibm-secrets-manager/releases/tag/v1.6.0
