### ISSUE TITLE
Secrets Manager DA feedback

### ISSUE THREAD

**Issue by ocofaigh** [terraform-ibm-modules/terraform-ibm-secrets-manager#79]
- Mark kms key crn as required variable in ibm_catalog.json
- Make `region` a dropdown of supported regions in ibm_catalog.json
- Make `service_plan` a dropdown picker in ibm_catalog.json
- Update the var description for `skip_kms_iam_authorization_policy` to ensure its clear that it should only be skipped if a policy is already in place on the account
- Remove `kms_region` variable and parse it from the CRN input variable

**Comment by tyao117** [comment]
Made some changes in the latest commit: https://github.com/terraform-ibm-modules/terraform-ibm-secrets-manager/pull/68/commits/08de0e40d6e9e4914207662af1277c323e7c6cc8

@ocofaigh if the standard flavor will now require input for an existing kms key, there would be no need to incorporate the `kms` module. Should the module `kms` be removed?
