### ISSUE TITLE
Review all SM DA related documentation

### ISSUE THREAD

**Issue by ocofaigh** [terraform-ibm-modules/terraform-ibm-secrets-manager#80]
The SM DA has 1 flavor currently:
- [standard](https://github.com/terraform-ibm-modules/terraform-ibm-secrets-manager/tree/main/solutions/standard)

The following items will need to be reviewed and updated where required:

- [ ] DA variable descriptions (in the DA's variables.tf file)
- [ ] The information in the ibm_catalog.json (labels, descriptions, features etc). Are we happy with the flavor naming?

**Comment by daniel-butler-irl** [comment]
existing_kms_guid description should ref `skip_kms_iam_authorization_policy`
![image](https://github.com/terraform-ibm-modules/terraform-ibm-secrets-manager/assets/10742925/2f4991f0-eee7-4f0b-ac3b-d090a93e4fcd)

**Comment by SirSpidey** [comment]
Partially addressed by https://github.com/terraform-ibm-modules/terraform-ibm-secrets-manager/pull/141
